management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always
management.health.circuitbreakers.enabled: true
rating:
  service:
    url: http://localhost:8081/v1/ratings
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      waitDurationInOpenState: 30
      failureRateThreshold: 60
      registerHealthIndicator: true
  instances:
    ratingService:
      baseConfig: default
      registerHealthIndicator: true